trigger:
  branches:
    include:
      - main

stages:
  - stage: DeployToDev
    displayName: 'Deploy to Development'
    jobs:
      - job: Deploy
        displayName: 'Deploy to Azure App Service'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'azureconnection'
              appName: 'app1'
              package: '$(Pipeline.Workspace)/drop/*.zip'
              deploymentMethod: 'zipDeploy'
            displayName: 'Deploy to Azure App Service'

  - stage: ApproveProduction
    displayName: 'Approval for Production'
    dependsOn: DeployToDev
    jobs:
      - job: Approval
        displayName: 'Approval Job'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: echo "Waiting for approval to deploy to Production..."
            displayName: 'Approval Step'

  - stage: DeployToProd
    displayName: 'Deploy to Production'
    dependsOn: ApproveProduction
    condition: succeeded('ApproveProduction')
    jobs:
      - job: Deploy
        displayName: 'Deploy to Azure App Service'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'azureconnection'
              appName: 'app1'
              package: '$(Pipeline.Workspace)/drop/*.zip'
              deploymentMethod: 'zipDeploy'
            displayName: 'Deploy to Azure App Service'